### ISSUE TITLE
Morning Clean-Up

### ISSUE THREAD

**Issue by cqyates** [Jaimetyler/project-x#21]
## Acceptance Criteria

- [x] set up link to javascript file in index.html
- [x] set up bootstrap link index.html
- [x] set up jquery link
- [x] put jay's background image in image folder
- [x] link reset.css and style.css in index.html
- [x] run tests in chrome

**Comment by cqyates** [comment]
Jay, 
I just need that picture from class to go in the image folder.  
Thanks, Corey

**Comment by brucechamblee** [comment]
Merged everything as on Monday night.
